[package]
name = "bustd"
authors = ["Vinícius R. Miguel <vrmiguel99@gmail.com>"]
version = "0.1.1"
edition = "2018"
readme = "README.md"
repository = "https://github.com/vrmiguel/bustd"
description = "Lightweight process killer daemon for out-of-memory scenarios"
categories = ["command-line-utilities", "memory-management"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = { version = "0.3.1", optional = true }
libc = "0.2.144"
cfg-if = "1.0.0"
daemonize = "0.5.0"
argh = "0.1.10"
memchr = "2.5.0"

[build-dependencies]
cc = "1.0.68"
libc = "0.2.97"

[dev-dependencies]
# Using a somewhat popular crate, `procfs`, to test our own
# implementation of proc-fs reads.
# Probably not the best decision possible but OK for now
procfs = { version = "0.14.2", default-features = false }

[features]
glob-ignore = ["glob"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
